---
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_terminal: yes
configure_osx: yes

configure_sudoers: no
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/deekim/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/workspace/deekim/dotfiles
dotfiles_files:
  - .aliases
  - .gitconfig
  - .gitignore
  - .hushlogin
  - .macos
  - .vimrc
  - .zshrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - switchaudio-osx
  - zsh-history-substring-search
  - ruby
  - kdoctor
  - r
  - pre-commit
  - git-lfs
  - direnv
  - docker
  - colima
  - fx
  - cue-lang/tap/cue
  - hyperfine
  - dive
  - diff-so-fancy
  - bat
  - kustomize
  - shellcheck
  - parquet-cli
  - awscli
  - fortune
  - autoconf
  - bash-completion
  - doxygen
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - n
  - php
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - wget
  - wrk
  - gcc
  - aspell
  - autojump
  - gnupg
  - gpg-agent
  - gradle
  - groovy
  - hub
  - imagemagick
  - m-cli
  - make
  - maven
  - octave
  - pinentry-mac
  - pssh
  - pup
  - python3
  - the_silver_searcher
  - tree
  - zplug
  - zshrc
  - zsh-completions
  - bazelisk
  - vault
  - starship
  - svn
  - miller
  - kubectl
  - helm
  - helmfile
  - txn2/tap/kubefwd
  - kubectx
  - pyenv
  - pyenv-virtualenv
  - terraform
  - jq
  - yq
  - tldr
  - k9s
  - lastpass-cli
  - watch
  - fzf
  - postgresql

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/bundle
  - homebrew/services
  - homebrew/cask-versions
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alacritty
  - slack
  - raycast
  - spotify
  - lastpass
  - visual-studio-code
  - zoomus
  - sublime-text
  - sublime-merge
  - vagrant
  - alfred
  - bartender
  - logitech-g-hub
  - iterm2
  - karabiner-elements
  - ticktick
  - moom
  - gpg-suite
  - kap
  - postman
  - virtualbox
  - xquartz
  - obsidian
  - stats
  - deckset
  - meetingbar
  - zulu8
  - font-fira-code
  - font-fira-mono
  - font-fira-mono-for-powerline
  - font-fira-sans
  - quitter

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
# bear, amphetamine
mas_email: ""
mas_password: ""

osx_script: "~/.macos --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
  # - name: drush
  #   state: present # present/absent, default: present
  #   version: "^8.1" # default: N/A
gem_packages:
  - name: cocoapods
  # - name: bundler
  #   state: present # present/absent/latest, default: present
  #   version: "~> 1.15.1" # default: N/A
npm_packages:
  - name: docsify-cli
  - name: awsp
pip_packages:
  - name: buku

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
