font:
  normal:
    family: Fira Code
    style: Regular
  bold:
    family: Fira Code
    style: Bold
  size: 17.0

shell:
  program: zsh
  args:
    - --login

key_bindings:
  - { key: T, mods: Command, action: CreateNewWindow }
