right_format = """$time"""

[character]
success_symbol = "[➜](bold bright-green)"
error_symbol = "[✗](bold bright-red) "

[time]
disabled = false
format = 'at [$time]($style) '
time_format = "%T"

[aws.region_aliases]
us-west-2 = "nuna"
